#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
skill_file="$repo_root/skills/gm-topic-engine/SKILL.md"
de_ai_skill_file="$repo_root/skills/gm-de-ai-article/SKILL.md"
battle_init_skill_file="$repo_root/skills/gm-battle/SKILL.md"
pk_skill_file="$repo_root/skills/gm-pk/SKILL.md"
build_harness_skill_file="$repo_root/skills/gm-harness-init/SKILL.md"
build_harness_reference_file="$repo_root/skills/gm-harness-init/references/file-templates.md"
build_harness_app_server_template_dir="$repo_root/skills/gm-harness-init/references/codex-app-server-node-template"
build_harness_app_server_template_readme="$build_harness_app_server_template_dir/README.md"
build_harness_app_server_template_package="$build_harness_app_server_template_dir/package.json"
build_harness_app_server_template_index="$build_harness_app_server_template_dir/index.js"
build_harness_app_server_template_main="$build_harness_app_server_template_dir/orchestrator/main.js"
build_harness_app_server_template_runner="$build_harness_app_server_template_dir/orchestrator/runner.js"
build_harness_app_server_template_state_machine="$build_harness_app_server_template_dir/orchestrator/state-machine.js"
build_harness_app_server_template_client="$build_harness_app_server_template_dir/runtime/app-server-client.js"
build_harness_app_server_template_console_reporter="$build_harness_app_server_template_dir/runtime/console-reporter.js"
build_harness_app_server_template_transport="$build_harness_app_server_template_dir/runtime/jsonrpc-transport.js"
build_harness_app_server_template_reducer="$build_harness_app_server_template_dir/runtime/event-reducer.js"
build_harness_app_server_template_approval="$build_harness_app_server_template_dir/runtime/approval-handler.js"
build_harness_app_server_template_generator="$build_harness_app_server_template_dir/agents/generator.js"
build_harness_app_server_template_evaluator="$build_harness_app_server_template_dir/agents/evaluator.js"
build_harness_app_server_template_report_writer="$build_harness_app_server_template_dir/tools/report-writer.js"
build_harness_app_server_template_state="$build_harness_app_server_template_dir/state/run_state.json"
build_harness_app_server_template_runtime_config="$build_harness_app_server_template_dir/config/runtime.json"
plan_task_skill_file="$repo_root/skills/gm-harness-plan-task/SKILL.md"

fail() {
  printf '%s\n' "$1" >&2
  exit 1
}

[ -f "$skill_file" ] || fail "missing skill file: $skill_file"

grep -F "name: gm-topic-engine" "$skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-topic-engine"
grep -F "description:" "$skill_file" >/dev/null || fail "skill frontmatter must declare a description"
grep -F "argument-hint: \"[想法、笔记、评论、草稿]\"" "$skill_file" >/dev/null || fail "skill frontmatter must declare the expected argument hint"
grep -F "# gm-topic-engine" "$skill_file" >/dev/null || fail "skill body must include the skill heading"

[ -f "$de_ai_skill_file" ] || fail "missing skill file: $de_ai_skill_file"

grep -F "name: gm-de-ai-article" "$de_ai_skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-de-ai-article"
grep -F "description:" "$de_ai_skill_file" >/dev/null || fail "skill frontmatter must declare a description"
grep -F "argument-hint: \"[文章草稿]\"" "$de_ai_skill_file" >/dev/null || fail "skill frontmatter must declare the expected argument hint"
grep -F "# gm-de-ai-article" "$de_ai_skill_file" >/dev/null || fail "skill body must include the skill heading"

[ -f "$battle_init_skill_file" ] || fail "missing skill file: $battle_init_skill_file"

grep -F "name: gm-battle" "$battle_init_skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-battle"
grep -F "description: Use when starting a new battle session" "$battle_init_skill_file" >/dev/null || fail "gm-battle description should describe when to use the skill"
grep -F '`pk_id`' "$battle_init_skill_file" >/dev/null || fail "gm-battle must describe generating a pk_id"
grep -F '只允许讨论方案，不允许编写、修改或提交任何代码' "$battle_init_skill_file" >/dev/null || fail "gm-battle must explicitly prohibit code changes during battle"
grep -F "last_implement_output_version" "$battle_init_skill_file" >/dev/null || fail "gm-battle must initialize implement-output version metadata"
grep -F "last_judge_output" "$battle_init_skill_file" >/dev/null || fail "gm-battle must initialize last_judge_output"
grep -F 'battle/sessions/<pk_id>/state.json' "$battle_init_skill_file" >/dev/null || fail "gm-battle must write per-session state files"
grep -F 'battle/sessions/<pk_id>/issues.json' "$battle_init_skill_file" >/dev/null || fail "gm-battle must write per-session issues files"
grep -F 'battle/latest.json' "$battle_init_skill_file" >/dev/null || fail "gm-battle must update latest battle index"
grep -F '"current_stage": "implement"' "$battle_init_skill_file" >/dev/null || fail "gm-battle must initialize the implement stage"
grep -F "# gm-battle" "$battle_init_skill_file" >/dev/null || fail "skill body must include the skill heading"

[ -f "$pk_skill_file" ] || fail "missing skill file: $pk_skill_file"

grep -F "name: gm-pk" "$pk_skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-pk"
grep -F "description: Use when an existing battle session already has state on disk" "$pk_skill_file" >/dev/null || fail "gm-pk description should describe when to use the skill"
grep -F "argument-hint: \"[pk_id] [stop]\"" "$pk_skill_file" >/dev/null || fail "gm-pk must accept an optional pk_id and stop flag"
grep -F 'battle/sessions/<pk_id>/state.json' "$pk_skill_file" >/dev/null || fail "gm-pk must read per-session state files"
grep -F 'battle/sessions/<pk_id>/issues.json' "$pk_skill_file" >/dev/null || fail "gm-pk must read per-session issues files"
grep -F 'battle/latest.json' "$pk_skill_file" >/dev/null || fail "gm-pk must describe latest-session resolution"
grep -F '整个 battle 是方案评审流程，不是编码流程。' "$pk_skill_file" >/dev/null || fail "gm-pk must define battle as plan review rather than coding"
grep -F '如果没有传 `pk_id`，优先读取 `battle/latest.json`' "$pk_skill_file" >/dev/null || fail "gm-pk must resolve the latest battle when pk_id is omitted"
grep -F 'last_implement_output_version' "$pk_skill_file" >/dev/null || fail "gm-pk must require implement-output version metadata"
grep -F 'implement-r{current_round}' "$pk_skill_file" >/dev/null || fail "gm-pk must gate the initial implement handoff with version metadata"
grep -F 'revise-r{current_round}' "$pk_skill_file" >/dev/null || fail "gm-pk must gate revised plan handoff with version metadata"
grep -F '如果 `battle/sessions/<pk_id>/state.json` 中还没有 `last_judge_output` 字段，应补上并设为空字符串' "$pk_skill_file" >/dev/null || fail "gm-pk must describe initializing last_judge_output when entering judge"
grep -F '> `last_judge_output` 为空。请先把裁判模型的输出写入 `battle/sessions/<pk_id>/state.json`，再运行 `/gm:gm-pk`。' "$pk_skill_file" >/dev/null || fail "gm-pk must block judge completion until last_judge_output exists"
grep -F -- '- 将 `current_actor` 更新为 `judge`' "$pk_skill_file" >/dev/null || fail "gm-pk must set current_actor to judge when stopping"
grep -F -- '- 将 `current_actor` 更新为 `none`' "$pk_skill_file" >/dev/null || fail "gm-pk must set current_actor to none when completed"
grep -F '只有 `last_judge_output` 已写入时，才能从 judge 进入 completed' "$pk_skill_file" >/dev/null || fail "gm-pk must document the judge completion gate"
grep -F '最新方案正文：' "$pk_skill_file" >/dev/null || fail "gm-pk judge prompt must include the latest proposal text"
grep -F '被判定为 rejected 的问题' "$pk_skill_file" >/dev/null || fail "gm-pk judge prompt must surface rejected issues"
grep -F '[RESOLVE ISSUE-001]' "$pk_skill_file" >/dev/null || fail "gm-pk revise prompt must require issue-id-based responses"
grep -F '[REJECT ISSUE-002]' "$pk_skill_file" >/dev/null || fail "gm-pk revise prompt must support explicit rejections by issue id"
grep -F '只有在相关时，再补充安全性、性能、合规性或表达质量问题' "$pk_skill_file" >/dev/null || fail "gm-pk challenge prompt should adapt review dimensions to the task"
grep -F '拿到裁判回复后，应将完整输出写入 `battle/sessions/<pk_id>/state.json` 的 `last_judge_output`，再运行一次 `/gm:gm-pk` 完成收尾。' "$pk_skill_file" >/dev/null || fail "gm-pk must explain the final judge handoff"
grep -F "# gm-pk" "$pk_skill_file" >/dev/null || fail "skill body must include the skill heading"

[ -f "$build_harness_skill_file" ] || fail "missing skill file: $build_harness_skill_file"

grep -F "name: gm-harness-init" "$build_harness_skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-harness-init"
grep -F "description:" "$build_harness_skill_file" >/dev/null || fail "skill frontmatter must declare a description"
grep -F 'argument-hint: "[目标项目，例如：为 skills manager 创建 harness]"' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must declare the expected argument hint"
grep -F '`<project>/harness/` = AI 开发系统（执行引擎）' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must define the harness boundary"
grep -F '`<project>/.harness/` = 项目给 harness 的接口层（说明书）' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must define the .harness boundary"
grep -F '`spec > rules > contract > resources > summary/report`' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must define information priority"
grep -F '`harness/` 不存在时，自动创建 `harness/`' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must auto-create harness when missing"
grep -F '`.harness/` 不存在时，自动创建 `.harness/`' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must auto-create .harness when missing"
grep -F 'Codex app-server' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must document the Codex app-server template branch"
grep -F 'references/codex-app-server-node-template/' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must point users to the app-server template directory"
grep -F '保留现有 harness 实现，继续执行 `.harness/` 初始化' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must keep initializing .harness even when harness already exists"
grep -F '只有在 `harness/` 缺失时，才将 `references/codex-app-server-node-template/` 复制到 `harness/`' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init must only copy the template when harness is missing"
grep -F "# gm-harness-init" "$build_harness_skill_file" >/dev/null || fail "skill body must include the skill heading"
! grep -E 'Python|python|registry\.py|\.py' "$build_harness_skill_file" >/dev/null || fail "gm-harness-init should no longer mention Python defaults"

[ -f "$build_harness_reference_file" ] || fail "missing reference file: $build_harness_reference_file"

grep -F 'harness/orchestrator/' "$build_harness_reference_file" >/dev/null || fail "gm-harness-init reference must include orchestrator templates"
grep -F '## `.harness/` 最小文件集' "$build_harness_reference_file" >/dev/null || fail "gm-harness-init reference must include project-side templates"
grep -F '### `project-rules.md`' "$build_harness_reference_file" >/dev/null || fail "gm-harness-init reference must define project rules templates"
grep -F 'package.json' "$build_harness_reference_file" >/dev/null || fail "gm-harness-init reference must describe the Node package entrypoint"
! grep -E 'Python|python|registry\.py|main\.py|runner\.py|agent\.py|files\.py|shell\.py|tests\.py|browser\.py|\.py' "$build_harness_reference_file" >/dev/null || fail "gm-harness-init reference should no longer mention Python templates"

[ -d "$build_harness_app_server_template_dir" ] || fail "missing template directory: $build_harness_app_server_template_dir"
[ -f "$build_harness_app_server_template_readme" ] || fail "missing template file: $build_harness_app_server_template_readme"
[ -f "$build_harness_app_server_template_package" ] || fail "missing template file: $build_harness_app_server_template_package"
[ -f "$build_harness_app_server_template_index" ] || fail "missing template file: $build_harness_app_server_template_index"
[ -f "$build_harness_app_server_template_main" ] || fail "missing template file: $build_harness_app_server_template_main"
[ -f "$build_harness_app_server_template_runner" ] || fail "missing template file: $build_harness_app_server_template_runner"
[ -f "$build_harness_app_server_template_state_machine" ] || fail "missing template file: $build_harness_app_server_template_state_machine"
[ -f "$build_harness_app_server_template_client" ] || fail "missing template file: $build_harness_app_server_template_client"
[ -f "$build_harness_app_server_template_console_reporter" ] || fail "missing template file: $build_harness_app_server_template_console_reporter"
[ -f "$build_harness_app_server_template_transport" ] || fail "missing template file: $build_harness_app_server_template_transport"
[ -f "$build_harness_app_server_template_reducer" ] || fail "missing template file: $build_harness_app_server_template_reducer"
[ -f "$build_harness_app_server_template_approval" ] || fail "missing template file: $build_harness_app_server_template_approval"
[ -f "$build_harness_app_server_template_generator" ] || fail "missing template file: $build_harness_app_server_template_generator"
[ -f "$build_harness_app_server_template_evaluator" ] || fail "missing template file: $build_harness_app_server_template_evaluator"
[ -f "$build_harness_app_server_template_report_writer" ] || fail "missing template file: $build_harness_app_server_template_report_writer"
[ -f "$build_harness_app_server_template_state" ] || fail "missing template file: $build_harness_app_server_template_state"
[ -f "$build_harness_app_server_template_runtime_config" ] || fail "missing template file: $build_harness_app_server_template_runtime_config"

grep -F 'codex app-server' "$build_harness_app_server_template_readme" >/dev/null || fail "template README must explain Codex app-server usage"
grep -F 'node harness' "$build_harness_app_server_template_readme" >/dev/null || fail "template README must describe the project-root node harness entrypoint"
grep -F '实时' "$build_harness_app_server_template_readme" >/dev/null || fail "template README must describe real-time console output"
grep -F '"harness:run"' "$build_harness_app_server_template_package" >/dev/null || fail "template package.json must expose harness:run"
grep -F '"node ./index.js"' "$build_harness_app_server_template_package" >/dev/null || fail "template package.json must point harness:run at index.js"
grep -F 'if (require.main === module)' "$build_harness_app_server_template_index" >/dev/null || fail "template root index.js must guard the CLI entrypoint"
grep -F 'runHarnessCli' "$build_harness_app_server_template_index" >/dev/null || fail "template root index.js must expose the CLI entrypoint"
! grep -F 'runHarnessCli().catch' "$build_harness_app_server_template_main" >/dev/null || fail "orchestrator/main.js should not self-execute the harness"
grep -F 'initialize' "$build_harness_app_server_template_client" >/dev/null || fail "template app-server client must initialize the Codex app-server connection"
grep -F 'turn/start' "$build_harness_app_server_template_client" >/dev/null || fail "template app-server client must start turns"
grep -F 'createConsoleReporter' "$build_harness_app_server_template_console_reporter" >/dev/null || fail "template console reporter must provide the real-time terminal reporter"
grep -F 'patch.current_phase !== current.current_phase' "$build_harness_app_server_template_runner" >/dev/null || fail "template runner must allow same-phase state writes on restart"
grep -F 'previousState' "$build_harness_app_server_template_runner" >/dev/null || fail "template runner must track previous state when updating run state"
grep -F 'item/commandExecution/requestApproval' "$build_harness_app_server_template_approval" >/dev/null || fail "template approval handler must handle command approvals"
grep -F 'item/fileChange/requestApproval' "$build_harness_app_server_template_approval" >/dev/null || fail "template approval handler must handle file change approvals"
grep -F '".harness/reports"' "$build_harness_app_server_template_runtime_config" >/dev/null || fail "template runtime config must point reports at .harness/reports"
grep -F '"approvalPolicy": "on-request"' "$build_harness_app_server_template_runtime_config" >/dev/null || fail "template runtime config must use the current approvalPolicy value"
grep -F '"sandbox": "workspace-write"' "$build_harness_app_server_template_runtime_config" >/dev/null || fail "template runtime config must use kebab-case workspace-write sandbox"
grep -F '"sandbox": "read-only"' "$build_harness_app_server_template_runtime_config" >/dev/null || fail "template runtime config must use kebab-case read-only sandbox"

[ -f "$plan_task_skill_file" ] || fail "missing skill file: $plan_task_skill_file"

grep -F "name: gm-harness-plan-task" "$plan_task_skill_file" >/dev/null || fail "skill frontmatter must declare name: gm-harness-plan-task"
grep -F "description:" "$plan_task_skill_file" >/dev/null || fail "skill frontmatter must declare a description"
grep -F 'argument-hint:' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task must declare an argument hint"
grep -F '# gm-harness-plan-task' "$plan_task_skill_file" >/dev/null || fail "skill body must include the skill heading"
grep -F 'contracts/' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task must reference contracts directory"
grep -F '仅限新建 contract' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task must restrict run_state.json update to new contracts only"
grep -F 'running' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task must handle running status"
grep -F 'npm run harness:run' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task must support the Node harness run command"
! grep -E 'Python|python|\.py' "$plan_task_skill_file" >/dev/null || fail "gm-harness-plan-task should no longer mention Python commands"
